project:
  type: website
  output-dir: docs

website:
  title: "Education Atlas's Project Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2024-team-education_atlas/tree/master

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2024" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    code-fold: true
    code-summary: "Kod Bloğunu Göster/Gizle"
    execute:
      echo: false
      output: true
      warning: false
      error: true
      cache: false
    include-in-header:
      - text: |
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    embed-resources: true
    code-tools: true
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

